### ISSUE TITLE
menu swipe is not working, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/CLCwebsite#15]

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman can I get more description this?

**Comment by JoshuaVSherman** [comment]
@JoshuaVSherman in cell phone mode, when you click the menu it displays, then you should be able to swipe the menu to the right to close it. This was working, but now it is broken. I think you broke it at some point when you were implementing the music player as it was getting in the way of the buttons or something. Anyway, the code is in app.html and appUtils.js, and app.js

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves There is still a problem with the menu swipe, it seems to only work the first time you open the menu and it will swipe closed, after that, there is no swipe anymore, please fix
