### ISSUE TITLE
Complete these additional fixes

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/CLCwebsite#24]
* [x] There is no scroll bar when I shrink the size of the window. Display the scrollbar when inbetween wide and cell phone, just hide scrollbar when on cell phone width, it hides too soon **DONE**

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman could you have a look at this video recording or resizing the window?
https://www.useloom.com/share/f4cce61d7a284b5194e7cf925784245d

I'm not sure I know exactly what it's needed.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves do you see the point where the picture of the church disappears but the text remains in the left column and there is just white space on the screen, that is the issue. It is fine on widescreen, it is fine on cellphone, but in between (ipad size, for example) it looks weird, please fix that so the text strethces accross the width there:
![image](https://user-images.githubusercontent.com/13340120/49290204-61438a00-f474-11e8-943a-d5b973e406ec.png)

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves also, any fixes you do here to CLC website, please apply where applicable to combined-front. Eventually, i'd like the shared code to be in its own node package we can install into both projects (and any future project), thanks

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves last time I checked, the second item above was still not fixed, please fix, thanks
