### ISSUE TITLE
Force the pages to load at the top

### ISSUE THREAD

**Issue by chemmom2** [WebJamApps/CLCwebsite#70]
If you navigate to a new page from the middle of a page, the new page loads in at the bottom!

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman when the page loads initially, the home link is not available. As a result, this doesn't work for the home button but for all the other links. will take care of this.

**Comment by JoshuaVSherman** [comment]
Ok change the nav link for Home to be /?reload=true

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman Fixed.

**Comment by chemmom2** [comment]
@DannyMcwaves Thanks!, works great, currently deployed at clc-dev.herokuapp.com
