### ISSUE TITLE
Toggle mobile menu does not work on Safari, please fix 

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/CLCwebsite#81]
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman  Looks like clicking the icon doesn't not work at all. It's somehow unclickable. clicking it with script in the console works. 
<img width="258" alt="screen shot 2019-01-03 at 8 36 58 pm" src="https://user-images.githubusercontent.com/16429468/50660473-c7518e80-0f97-11e9-805c-457a904ff98d.png">

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves so can you just write a vanilla JavaScript click event or something so it will work, I know that it is strange and interesting to try and figure out why it is not working on iphone, but for now, just get it to work would be great, thanks

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves maybe try putting an <a click.delegate="toggleMobileMenu('open')">
around the <i> ?

**Comment by DannyMcwaves** [comment]
Sure. would do that. 
If you click it programmatically, all subsequent clicks on the screen works.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves super weird, if you think you know what is the cause (Aurelia maybe), we should post a bug on one of their project pages, maybe the aurelia templating page for click.delegate or something

**Comment by DannyMcwaves** [comment]
I've not fully figured it out yet. But I should come up with a fix for this by close of the day.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves here it is, do this!!!   https://github.com/aurelia/binding/issues/263
