### ISSUE TITLE
Slideshows do not start right away  on widescreen, they work fine on cellphone size, please fix

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/CLCwebsite#98]
@DannyMcwaves please fix the slideshows because if I go from cellphone to widescreen, they stop, sometimes they start again after a while, but not sure what is going on. Can we code something that stops the cellphone slideshow and starts the widescreen slideshow if that variable is true or false maybe?
or maybe we should not have to instances of the slideshow and use the aurelia templating if.find to show/hide them based on screen size, whatever you think is best way to handle it while not breaking the sizing adjustments I did in css. thanks

  @DannyMcwaves also can you copy over the react unit tests for this (from combined-front) so we have the code coverage again, thanks

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman when your mouse is hovering over the slider component, it freezes that particular frame/image until you mouse is out of the component.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves hello, and happy Valentines Day. If you just go here (wait for it to load cause it is slow with it being the free dev site), then click the Youth Ministry side menu, you will see that the slideshow does not start right away, then click the Children & Family side menu link, then click back to the Youth Ministry. Notice how the slideshows do not start right away.  http://clc-dev.herokuapp.com/youth

**Comment by JoshuaVSherman** [comment]
Strange but in cellphone displays they work great

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves after looking at this issue again, indeed you are correct that it appears related to where the cursor is positioned, however, the slides stop even if it is to the far left or right of the photo. Could you please fix that so it only stops if the cursor is on the photo please. Also change the cursor to pointer in that case too. Thanks

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves please fix the width of the picture on the /music page now, it should be the same width as the text area below the picture, thanks

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves so I just looked at the slideshows on cellphone and now the pictures are not sized properly, so you probably need to put those styles back the way that they were previously and figure out a different way to prevent the slideshows from pausing when the cursor is on the whitespace next the photos(on widescreen), thanks

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves also reminder that the music page picture is not correct width either

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves the pictures are still not correct for the /youth page on cellphone.  Please look, the widths are off page

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves if I turn my cellphone horizontal,  they look great, although not stretched to max width, please fix

**Comment by DannyMcwaves** [comment]
@joshuaVSherman, could describe exactly what you mean? do you mean the
entire image is not getting displayed?

**Comment by JoshuaVSherman** [comment]
Clc-dev.herokuapp.com

Open the youth page on cellphone

The picture width is beyond the width of the screen

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves I was able to reproduce the issue on my chrome desktop by choosing the pixel2
![image](https://user-images.githubusercontent.com/13340120/53589942-aacc6f80-3b5e-11e9-9fc6-88be0215f020.png)

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves sorry, this is still not correct. See the /family page, the pictures are now squished, please fix
![image](https://user-images.githubusercontent.com/13340120/54029326-0063d600-4176-11e9-85d9-fba3cd03c2c0.png)

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves Also, on widescreen please change cursor to hand when hovering over the slideshow to indicate why it is stopping. It is confusing when I hover over the white space next to a picture and it stops, I understand that the pictures are not all the same width. It would be nicer if the slideshow stops only when i'm hovering over the image.

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman as you're aware, the dimensions of the images are not all the same.

The picture-slider component uses a library for the slider. the library keeps height of all the slides the same.
As a result

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves fork the library, make the code changes there to support having variable picture sizes, install it into our project as your github forked version
make a pull request back to the project, telling them that you made this improvement
for the immediate fix, just make the pictures display correctly and make the cursor change to hand when hovering over the slideshow (even when it is white space, I understand this limitation currently)

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves the /youth page, pictures are off page on cellphone, please fix
![image](https://user-images.githubusercontent.com/13340120/54091899-0ddab500-435c-11e9-9782-e2a617788b0f.png)

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves this morning after reinstall and testing again, I noticed that the pictures are being stretched, please fix
![image](https://user-images.githubusercontent.com/13340120/54122112-9005c080-43d2-11e9-9d3b-9464024e44df.png)

**Comment by DannyMcwaves** [comment]
@JoshuaVSherman, this is just for the youth page?

It looked OK on cellphone chrome. that's pixel 2.

**Comment by JoshuaVSherman** [comment]
@DannyMcwaves yes, the goal here is to allow the end user ability to put any picture they want into a slideshow and it will work, where they do not need to crop or resize pictures to any particular size.
